@echo off
set SISTEMA_COSTOS_DB_BACKEND=pervasive
set SISTEMA_COSTOS_PERVASIVE_SERVER=192.168.1.168
set SISTEMA_COSTOS_PERVASIVE_DBQ=C:\USERS\TI\DESKTOP
set SISTEMA_COSTOS_PERVASIVE_USER=Master
set SISTEMA_COSTOS_PERVASIVE_PASSWORD=COSTPP
"e:\SISTEMA DE COSTOS\.venv\Scripts\python.exe" "e:\SISTEMA DE COSTOS\main.py"
